# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'childmind' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for childmind
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'

  target 'childmind-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'childmindTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'childmind-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for childmind-tvOS

end
